### ISSUE TITLE
source code encoding problem

### ISSUE THREAD

**Issue by sisyphusman** [marukrap/RoguelikeTutorial#1]
이렇게 자료를 남겨주셔서 감사합니다

혹시 파트6~ 파트8에 문자열 경고와 함께 상수를 찾을 수 없다는 에러가 뜨신다면,

에러 코드가 나오는 파일로 각각 이동하셔서 파일 - 다른 이름으로 저장 - 저장 버튼 옆 화살표 - 인코딩하여 저장

유니코드(서명 있는 UTF-8) - 코드 페이지 65001로 저장하여 덮어쓰기를 하시면 잘 됩니다

참고자료 : https://gist.github.com/grizlupo/a9746b9ff99a76582c29ca6f956b219b

**Comment by marukrap** [comment]
제가 작업할 때 UTF-8 인코딩을 썼을 텐데 깃허브 업로드/다운로드 과정에서 인코딩이 바뀌는 건지
이전에도 비슷한 문제가 있다는 말을 들었던 것도 같네요.
깃허브를 자주 사용하지는 않아서 정확한 원인까지는 저도 잘 모르겠습니다.
그리고 이쪽 튜토리얼은 국내 커뮤니티(로그라이크 갤러리)에서 재미삼아 연재하다가 드랍한 저장소인데
완전한 튜토리얼은 https://github.com/marukrap/RoguelikeTutorial2020 이쪽을 참고하셔도 좋을 것 같습니다.
